# Generated by Django 6.1 on 2026-09-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Wagon', 'Wagon'), ('Liftback', 'Liftback')], default='Sedan', max_length=20),
        ),
    ]
